### ISSUE TITLE
Error: Unexpected error while acquiring application default credentials: read ECONNRESET

### ISSUE THREAD

**Issue by dgadelha** [googleapis/nodejs-datastore#39] opened 2018-01-04 18:06 UTC
```
Error: Unexpected error while acquiring application default credentials: read ECONNRESET
    at /user_code/node_modules/@google-cloud/datastore/node_modules/google-gax/node_modules/google-auth-library/lib/auth/googleauth.js:196:35
    at /user_code/node_modules/@google-cloud/datastore/node_modules/google-gax/node_modules/google-auth-library/lib/auth/googleauth.js:229:32
    at Request._callback (/user_code/node_modules/@google-cloud/datastore/node_modules/google-gax/node_modules/google-auth-library/lib/transporters.js:79:36)
    at self.callback (/user_code/node_modules/@google-cloud/datastore/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/user_code/node_modules/@google-cloud/datastore/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)"
```

#### Environment details

  - Environment: Google Cloud Functions
  - Node.js version: [6.11.5](https://cloud.google.com/functions/docs/writing/#the_cloud_functions_runtime)
  - npm version: 5.6.0 (local, to deploy)
  - @google-cloud/datastore version: 1.3.3

#### Steps to reproduce

  1. Attempt to read/write a Datastore entry inside Google Cloud Functions
  2. Randomly fail (just like the previous issue)

**Comment by dgadelha** [comment] 2018-01-05 21:17
Been using @ChrisBartonLC's suggestion (https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2374#issuecomment-349842155) as workaround.

**Comment by ChrisBartonLC** [comment] 2018-01-05 22:07
@dgadelha if you are not already a member of the cloud-functions-beta-testers group I recommend you join because there is more up-to-date information of this issue there, see "PubSub subscription stops delivering messages to CloudFunction" which covers both datastore and pubsub, basically it is now reproducible and so no doubt will be fixed in time.

**Comment by ChrisBartonLC** [comment] 2018-01-05 22:13
@dgadelha FYI is case you don't know, you can pin to these versions as a workaround:

"@google-cloud/datastore": "1.1.0",
"@google-cloud/pubsub": "0.14.0",

**Comment by dgadelha** [comment] 2018-01-10 00:14
@ChrisBartonLC I moved Datastore to 1.1.0, and I have this frequently: `Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information." `

**Comment by ChrisBartonLC** [comment] 2018-01-10 11:17
Ah unfortunately that means you will need to embed the service account which is what we do:

client = { datastore: require('@google-cloud/datastore')({ credentials: service_account }) }

We actually encrypt our service account with Cloud KMS but I guess you could just include the json in your function as long as your don't accidentally commit it. 

Another option is to temporality deploy to Appengine Flex (see below). I though that would be a lot of work but it turned out to be really easy.

-------------------------
app.yaml

service: lc-api-product
runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
-------------------------

-------------------------
app.js

const express = require('express')

const api = express()

const api_port = process.env.PORT || 8080

    api.listen(api_port, () => {
      const ctx = path('listen')
      log.info('App listening', { context: ctx, fields: { api_port: api_port } })
    })

api.get('/', (req, res) => {
  const ctx = path('api_product')
  log.debug('ENTER', { context: ctx })

  res.status(200).send('Hello, world!').end()
})

api.get('/product/v1/brands', (req, res) => {
  const ctx = path('api_product_brands')
  log.debug('ENTER', { context: ctx })

  require('./api/product/brands/do').invoke(req, res)
})
-------------------------

**Comment by dgadelha** [comment] 2018-01-30 21:45
Ok so, I have embedded the service account in the code, now the issue that's showing up is:

```
Error: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "read ECONNRESET".
    at FirebaseAppError.Error (native)
    at FirebaseAppError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAppError (/user_code/node_modules/firebase-admin/lib/utils/error.js:119:28)
    at /user_code/node_modules/firebase-admin/lib/firebase-app.js:125:23
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Seems to not be related to Datastore till now, just with FCM.

**Comment by ChrisBartonLC** [comment] 2018-01-30 23:18
I used to get those messages and had to downgrade my datastore client to @google-cloud/datastore": "1.1.0"

**Comment by dgadelha** [comment] 2018-01-30 23:23
Yeah I have on my package.json `"@google-cloud/datastore": "1.1.0"`

**Comment by ChrisBartonLC** [comment] 2018-01-30 23:32
so this is the Firebase service account right? AKA Firebase SDK?

log.info('Creating firebase app reference', { context: path('app'), fields: { type: type } })

    return secrets.secret_json(type)
      .then(service_account => {
        const app = firebase_admin.initializeApp({
          credential: firebase_admin.credential.cert(service_account),
          databaseURL: `https://${service_account.project_id}.firebaseio.com`
        }, uuid())

        _apps.set(type, app)

        return Promise.resolve(_apps.get(type))
      })

**Comment by ChrisBartonLC** [comment] 2018-01-30 23:38
So we have two service accounts in play, one to talk to GCP resources and one downloaded from the the FB project we use.

**Comment by dgadelha** [comment] 2018-01-31 17:08
Didn't see this issue happen till now, thanks!

**Comment by stephenplusplus** [comment] 2018-06-21 14:43
> Error: Unexpected error while acquiring application default credentials: read ECONNRESET - @dgadelha 

This error should be retried automatically. Can you show the code are you using that returns this error? If it's anything to do with a readable stream, it's possible we have a fix coming in a release shortly.

**Comment by dgadelha** [comment] 2018-06-22 01:52
Hey Stephen,

Unfortunately, the project I was working on was canceled.

But the issue happened randomly when doing anything related to Datastore (read/write data).

Our code was hosted on Google Cloud Functions and we used both Datastore and Realtime Database for data storage. We had no problems while using Realtime Database, but Datastore queries used to throw a 500 with the errors I described above.

Thanks!

**Comment by stephenplusplus** [comment] 2018-06-22 15:51
@ChrisBartonLC I think you might have a better handle on the status of this issue, as it stands now. Would you catch me up?

**Comment by Arqu** [comment] 2018-08-05 21:55
I have the same issue happening, but on Pub/Sub write from Cloud Functions. I've pinpointed it down to it happening only when updating a CF while having live data in Pub/Sub, for a split moment it keeps spitting these out before going back to normal. Reproducible 1/1 for me.

**Comment by stephenplusplus** [comment] 2018-09-14 17:30
@Arqu do you have a service account JSON file deployed, or are you using automatic authentication?

**Comment by Arqu** [comment] 2018-09-17 20:58
Automatic auth since everything lives in the same project space. Tbh it's not a real issue right now and only happens for a split period during deployment. Other than that it is ok.
I had the same/similar error happening on k8s but that is another story related to the cluster permissions/service keys.

**Comment by JustinBeckwith** [comment] 2019-01-15 04:52
👋 Greetings folks - it looks like the issues here were intermittent, and have since cleared up.  If folks are still running into this - please let us know!  I'm going to go ahead and close this one out for now.

**Closed by JustinBeckwith** 2019-01-15 04:52 UTC
Labels: :rotating_light:, priority: p1, type: bug
