### ISSUE TITLE
Missing explicit dependency on Long.js

### ISSUE THREAD

**Issue by runeh** [googleapis/nodejs-datastore#345] opened 2019-03-04 12:59 UTC
The `datastore.d.ts` and `entity.d.ts` files that are included in the build uses Long.js. There are several type definitions there that use the `Long` type.

Long.js is not declared in package.json as a direct dependency of  `nodejs-datastore`, which causes compilation to fail in some monorepo situations where dependencies may get hoisted. In our case, using yarn.

It works as expected without monorepos, because long.js is a transitive dependency from protobuf.js

  - `@google-cloud/datastore` version: 3.1.1

#### Steps to reproduce

Sorry, wasn't able to reproduce outside of our monorepo, which I'm not able to share.

Cheers

**Comment by stephenplusplus** [comment] 2019-03-04 17:14
@joecervino @JustinBeckwith would you mind taking a look?

**Comment by callmehiphop** [comment] 2019-03-04 17:19
Protobufjs does export a very [simple Long interface](https://github.com/dcodeIO/protobuf.js/blob/master/index.d.ts#L1822), which I assume is what's meant to be referenced, however the generated files reference a global `Long`. It is pretty unclear to me where that comes from and why we don't see this error elsewhere. Looks like a pbjs bug to me (maybe?)

**Comment by JustinBeckwith** [comment] 2019-03-04 19:25
Well, that was unexpected:
https://github.com/googleapis/nodejs-datastore/pull/346

I found a bug, just not this bug 🤦‍♂️

**Comment by JustinBeckwith** [comment] 2019-03-04 19:26
@runeh We're going to need some help reproducing this one.  Is there any chance you could create a small repo that shows the problem?

**Comment by runeh** [comment] 2019-03-04 22:29
I've figured it out! Mostly a config issue. There's a repro here: https://github.com/runeh/goog-datastore-repro . It also triggers the duplexify thingy mentioned further up.

Turns out, in our monorepo, we set `types: ["node", "jest"]` in our tsconfig. This was added because without it tsc finds multiple versions of those library definitions and gets perturbed.

Anyway, when that setting is there, it prevents any other global declarations from being imported. From [the typescript docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)

> Keep in mind that automatic inclusion is only important if you’re using files with global declarations (as opposed to files declared as modules). If you use an import "foo" statement, for instance, TypeScript may still look through node_modules & node_modules/@types folders to find the foo package.

(my tsconfig-fu was certainly not strong enough to remember this off the top of my head :(  )

So, in our monorepo, adding `long` to the list of types makes it stop complaining about missing Long type.

I'd still contend that directly relying on a type that isn't an explicit dependency is a bug, but it wasn't what was the problem in this case.

Some easily searchable prose in the datastore readme explaining what causes this error message would probably be useful for those that come after us, if there isn't some other more explicit way to reference the types :)

**Comment by callmehiphop** [comment] 2019-03-06 00:20
@JustinBeckwith any chance of seeing types for gapic files soon?

**Comment by JustinBeckwith** [comment] 2019-03-06 05:38
Ok - so I did some playing around of my own here :) Thanks for the perfect repo @runeh!  Your intuition was right.  You can fix this 1 of 2 ways:
- Completely delete your `types` section from the `tsconfig`
- Update your `types` section to include `long` as one of the options

I'm kinda shocked that the `types` property in `tsconfig` even exists.  It's basically saying "hey, ignore mah types".  

Outside of that change - I don't *think* there's anything we can really do here, so I'm going to close this out for now.

**Comment by SimenB** [comment] 2019-03-06 08:57
I strongly disagree there's nothing you can do here - you should not depend on a global type definition somewhere in `node_modules` providing you with the type you refer to. You should import it from the package you depend on (and it seems you don't even depend on `@types/long`, so it comes in transitively from `protobufjs`).

Adding `import Long from 'long';` at the top of `node_modules/@google-cloud/datastore/build/proto/datastore.d.ts` also fixes the error for me, without changing `tsconfig.json` in the provided reproduction repo.

However, I still get an error due to another undeclared dependency
![image](https://user-images.githubusercontent.com/1404810/53868117-9290a080-3ff5-11e9-8e75-7efb1be5b7ce.png) so even removing `types` definition doesn't completely fix the error.

All `@types/` packages that end up in your own distributed `d.ts` files should be declared as dependencies, not dev dependencies - otherwise you force consumers to figure out which version of the type defs you depend on and install them. In the case of `duplexify` above for instance, installing `@types/duplexify@latest` doesn't work

![image](https://user-images.githubusercontent.com/1404810/53868202-ce2b6a80-3ff5-11e9-8049-1d1e44e3fe01.png)

That's not from the package in this repo specifically, but I think it gets the point across nonetheless 🙂

**Closed** 2019-03-06 20:24 UTC
Labels: priority: p2, type: bug
