### ISSUE TITLE
Error: 13 INTERNAL: Received RST_STREAM with code 2

### ISSUE THREAD

**Issue by SUM-Soft** [googleapis/nodejs-datastore#679] opened 2020-06-10 19:27 UTC
Hi!

Getting the following error periodically (1-2 times a day)

```
A 2020-06-10T18:35:53.594123Z (node:14) UnhandledPromiseRejectionWarning: Error: 13 INTERNAL: Received RST_STREAM with code 2 
A 2020-06-10T18:35:53.594173Z     at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:30:26) 
A 2020-06-10T18:35:53.594187Z     at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:175:52) 
A 2020-06-10T18:35:53.594267Z     at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141) 
A 2020-06-10T18:35:53.594293Z     at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181) 
A 2020-06-10T18:35:53.594306Z     at Http2CallStream.outputStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74) 
A 2020-06-10T18:35:53.594318Z     at Http2CallStream.maybeOutputStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22) 
A 2020-06-10T18:35:53.594330Z     at Http2CallStream.endCall (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18) 
A 2020-06-10T18:35:53.594342Z     at ClientHttp2Stream.<anonymous> (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:403:22) 
A 2020-06-10T18:35:53.594356Z     at ClientHttp2Stream.emit (events.js:315:20) 
A 2020-06-10T18:35:53.594367Z     at emitCloseNT (internal/streams/destroy.js:69:8) 
A 2020-06-10T18:35:53.594394Z (node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) 
A 2020-06-10T18:35:53.594405Z (node:14) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
A 2020-06-10T18:35:54.059739Z Error: 13 INTERNAL: Received RST_STREAM with code 2
    at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at ClientHttp2Stream.<anonymous> (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:403:22)
    at ClientHttp2Stream.emit (events.js:315:20)
    at emitCloseNT (internal/streams/destroy.js:69:8) { 
A 2020-06-10T18:35:54.059769Z   code: 13, 
A 2020-06-10T18:35:54.059794Z   details: 'Received RST_STREAM with code 2', 
A 2020-06-10T18:35:54.059803Z   metadata: Metadata { internalRepr: Map {}, options: {} }, 
A 2020-06-10T18:35:54.059813Z   note: 'Exception occurred in retry method that was not classified as transient' 
A 2020-06-10T18:35:54.059821Z }
```
#### Environment details

  - OS: Cloud Run
  - Node.js version: node:lts-slim
  - npm version:  6.14.5
  - `@google-cloud/datastore` version: 6.0.0

Thanks!

**Comment by BenWhitehead** [comment] 2020-06-15 22:12
@schmidt-sebastian Does this look like the same error we're seeing in Firestore?

**Comment by BenWhitehead** [comment] 2020-06-15 22:13
@SUM-Soft Can you confirm if you're using Cloud Datastore or Cloud Firestore in Datastore Mode?

**Comment by schmidt-sebastian** [comment] 2020-06-15 22:23
It would shock me if this wasn't the exact same as https://github.com/googleapis/nodejs-firestore/issues/1023

**Comment by SUM-Soft** [comment] 2020-06-16 05:02
> @SUM-Soft Can you confirm if you're using Cloud Datastore or Cloud Firestore in Datastore Mode?

Using Cloud Firestore in Datastore mode

**Comment by mdobson** [comment] 2020-07-09 21:57
We see this issue in using Cloud Datastore within Cloud Run as well.

**Comment by radvansky-tomas** [comment] 2020-07-10 09:11
I am seeing this constantly now...every time I am trying to write object to newly created collection (from auth trigger in firebase cloud functions).

**Comment by damienromito** [comment] 2020-07-12 16:33
I got this on OnDelete triggers

Yesterday
![Screen Shot 2020-07-12 at 18 33 07](https://user-images.githubusercontent.com/603808/87251726-22f2b700-c46e-11ea-85c4-a0cd9578b998.png)


Today
![Screen Shot 2020-07-12 at 18 32 16](https://user-images.githubusercontent.com/603808/87251709-06ef1580-c46e-11ea-987b-cc0254ee6d1c.png)
![Screen Shot 2020-07-12 at 18 32 38](https://user-images.githubusercontent.com/603808/87251713-11111400-c46e-11ea-9279-6c7c383834e4.png)

**Comment by rdev-software** [comment] 2020-07-12 20:01
Show how you configure your admin app, if you dont have same issue as above

**Comment by SUM-Soft** [comment] 2020-07-21 17:22
The error still occurs with @google-cloud/datastore version: 6.1.0
Any progress on this issue?

**Comment by zdenda-online** [comment] 2020-10-15 22:53
We see the same. It usually happens for us when we do quite a heavy load of database writes in Node.js GCP function (nodejs10) during the migration of data. I tried to "relax" the calls putting random 1-20ms "sleep" in between writes but it did not help.

And yes, we are using Datastore in Firestore mode. Datastore client libraries version 6.2.0.

Any progress on this?

**Comment by biendinh** [comment] 2020-10-26 09:09
Same here on firebase function.
Db: Cloud Firestore 
![Screenshot from 2020-10-26 16-09-06](https://user-images.githubusercontent.com/23469429/97153768-9c0be500-17a5-11eb-979d-a0bfaa84b016.png)

**Comment by fgeorgsson** [comment] 2020-11-10 11:43
I see this error to while using @google-cloud/firestore 4.3.0 in Google App Engine flexible with NodeJS 12.
I know this issue was about datastore mode, but since it happens in native mode as well there might be shared code.

We run about 12 batches on startup, which run concurrently or close to each other in time. Most have around 10-20 writes, a few have 240 writes in each batch.

**Comment by eli-stewart** [comment] 2020-12-10 06:42
I am seeing this as well. I am running a Typescript React App with a node.js server. The server is throwing this error fairly regularly. Something like once an hour. I also get this similar error: @firebase/firestore: Firestore (7.19.1): Connection GRPC stream error. Code: 14 Message: 14 UNAVAILABLE: Stream refused by server but about 20% as frequently.

I had a crash on my site on Monday where I was not able to read or write the database and I am trying to figure out if its related.

These are the 3 types of errors I am receiving of this type:
`@firebase/firestore: Firestore (7.19.1): Connection GRPC stream error. Code: 13 Message: 13 INTERNAL: Received RST_STREAM with code 2
@firebase/firestore: Firestore (7.19.1): Connection GRPC stream error. Code: 14 Message: 14 UNAVAILABLE: Stream refused by server
@firebase/firestore: Firestore (7.19.1): Connection GRPC stream error. Code: 13 Message: 13 INTERNAL: Received RST_STREAM with code 0
`

**Comment by alexbouchardd** [comment] 2020-12-10 23:48
Hi, I'm seeing the same error using Firestore for Datastore when writing from a gcloud function. It's occurs rarely and seemingly randomly. 

`Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)`

**Comment by zdenda-online** [comment] 2021-02-04 07:59
Any update?

By the way, I don't agree this should have priority p2 = moderate importance. This breaks the base use of the service.

**Comment by schmidt-sebastian** [comment] 2021-02-04 20:29
We are working on this with multiple engineers and trying to come with mitigation strategies. Unfortunately, this is more difficult than anticipated.

**Comment by zdenda-online** [comment] 2021-02-04 20:46
@schmidt-sebastian ok thanks for the info. Good luck with that :-) Was unsure as I see Open bug with no assignee.

**Comment by binajmen** [comment] 2021-02-24 15:46
Thank you @schmidt-sebastian for the follow up.

Please keep us in the loop when things are moving. I'm having the same issue with Cloud Run + Firestore.

**Comment by tohagan** [comment] 2021-03-09 02:08
Saw one of these in a firebase async onRequest call (Node 10 runtime) on 02/15/2021 

Here's the stack ...
```
Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at process.nextTick (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by dronpopdev** [comment] 2021-03-12 12:35
I got this on `onCreate` triggers. Cloud Firestore + Cloud Functions.

> Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET
>     at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
>     at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
>     at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
>     at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
>     at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
>     at processTicksAndRejections (internal/process/task_queues.js:79:11)

More details. I have created 15 objects. Each object was created approximately once every 20 seconds. It happened on March 12th.

**Comment by bcoe** [comment] 2021-03-12 23:25
@dronpopdev could you ensure the latest version of `@grpc/grpc-js` is in your package-lock.json (https://www.npmjs.com/package/@grpc/grpc-js) redeploy your application, and share the latest version of the error message -- if you're still running into issues.

We've been working to add improved error messages to the library.

**Comment by locona** [comment] 2021-03-16 11:40
I had the same error below, 
but I removed async/await and it worked, so I hope that gives you some clues.


environment:  
- Firebase functions 
- Node 12
- firebase-admin: 9.5.0
- firebase-functions: 3.13.2

```
Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at process.nextTick (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```



**failed**
```
functions.https.onCall(async (data, context) => {

  await ....
})
```


**success**
```
functions.https.onCall((data, context) => {

  ....
})

```

**Comment by LKNSI** [comment] 2021-03-30 22:41
Seeing these on non-google connections with gRPC. But while using a google gRPC library that has it's own gRPC connection within the context of the call made on our applications. Near identical message even when not using a google library.

i.e. <Microservice> -> (grpc connection) -> <Server> -> <Google Library that has a streaming gRPC connection (in our case speech to text)> -> <Response to microservice>

`Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
    at Object.callErrorFromStatus (<redacted>/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (<redacted>/node_modules/@grpc/grpc-js/build/src/client.js:387:49)
    at Object.onReceiveStatus (<redacted>/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at <redacted>/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)`

**Comment by vishalvijay** [comment] 2021-05-15 11:11
```
Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET
at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31)
at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:176)
at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336)
at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299)
at (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145)
at processTicksAndRejections (internal/process/task_queues.js:79)
```

Facing same issue with Firebase pubsub schedule function 

```ts
functions
  .region('asia-south1')
  .pubsub.schedule('every 1 minutes')
  .onRun(async () => {
    await theWork();
  });
```

**Comment by tfalvo** [comment] 2021-05-17 18:46
Facing exactly the same issue with `Cloud Tasks`: 
 
```
Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET
    at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11) 
```

This happens quite rarely, but when happening, it's not in a context of massive task creation, just a single task created :

```
await this.client.createTask({
      parent: queueName,
      task: {...}
});
```

**Comment by sharechat-dhruvsehgal** [comment] 2021-05-21 11:08
@tfalvo , do let us know if you are able to solve above problem. Facing similar problem with cloud task.

**Comment by Chm-vinicius** [comment] 2021-06-09 19:08
Same issue here, when try to migrate db from realtimedatabe to firestore, on localhost with small sample of db the migration function works very well, but when i use entire legacy db i got this errors and emulators got shutdown:


`Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
    at Object.callErrorFromStatus (workspace\functions\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (workspace\functions\node_modules\@grpc\grpc-js\build\src\client.js:176:52)
    at Object.onReceiveStatus (workspace\functions\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:336:141)
    at Object.onReceiveStatus (workspace\functions\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:299:181)
    at workspace\functions\node_modules\@grpc\grpc-js\build\src\call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Caused by: Error
    at WriteBatch.commit (workspace\functions\node_modules\@google-cloud\firestore\build\src\write-batch.js:413:23)
    at DocumentReference.set (workspace\functions\node_modules\@google-cloud\firestore\build\src\reference.js:350:14)
    at userIterator (workspace\functions\dbMigrator.js:270:28)
    at workspace\functions\dbMigrator.js:276:5
    at local\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:604:16
    at runFunction (local\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:583:15)
    at runHTTPS (local\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:603:11)
    at handler (local\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:532:23)
    at Layer.handle [as handle_request] (local\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)        
    at next (local\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:137:13)`

**Comment by odira1** [comment] 2021-06-20 03:40
Had this error happen after a couple of deletes on datastore, resolved it by ensuring that the process exited properly with process.exit(0). hope this helps someone, cheers :)

**Comment by crwilcox** [comment] 2021-07-22 21:35
In order for us to gather feedback better, please add any further details to the Firestore issue at googleapis/nodejs-firestore#1023. The root cause is likely the same and it seems better to gather feedback in a single place. Feel free to add there if you see an issue.

**Comment by meredithslota** [comment] 2022-05-10 18:52
Closing this out as discussion and investigation have continued in the issue linked above, and we are optimistic that a fix has been found and implemented, see here: https://github.com/googleapis/nodejs-firestore/issues/1023#issuecomment-1093017154 If this issue is _not_ fixed for you, please add your repro steps to that issue.

**Closed by meredithslota** 2022-05-10 18:52 UTC
Labels: priority: p2, type: bug, external, api: datastore
