### ISSUE TITLE
v4 doesn't release resource 

### ISSUE THREAD

**Issue by ert78gb** [googleapis/nodejs-datastore#421] opened 2019-06-02 14:14 UTC
Thanks for stopping by to let us know something could be better!

The library does not release a resource and the unit tests don't exist.
Is there a new command that we have to call before exiting from the application?

#### Environment details

  - OS: Mac, Linux, Windows
  - Node.js version: latest of  8, 10, 11
  - npm version: provided by node 
  - `@google-cloud/datastore` version: 4.0.0

#### Steps to reproduce

  1. `$ docker pull google/cloud-sdk:latest`
  2. `$ git clone https://github.com/ert78gb/google-datastore-emulator.git`
  3. `$ cd google-datastore-emulator`
  4. `$ npm i`
  5. `$ npm install --no-save @google-cloud/datastore`
  6. `$ npm test`

All test is pass, but mocha does not exists. The reason is there is a resource, timer, promise that running in the background and mocha waiting for the exit.

The 3.1.2 version of the lib worked perfectly, but something changed. You can see it in the travis build logs https://travis-ci.org/ert78gb/google-datastore-emulator/builds

I don't want to use `process.exit()` at the end of the test, because it hides resource release problems and it is also not a good practice. 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by laljikanjareeya** [comment] 2019-06-20 12:51
I tried with both the version of `@google-cloud/datastore`, but the behavior is same in both version. Please confirm, it is working with `@google-cloud/datastore` 3.1.2 version.

if not than you have to mention explicitly `--exist` in mocha command as default behavior of mocha has been changed since mocha 4.x version.

Please refer [this](https://github.com/chaijs/chai-http/issues/178#issuecomment-336602457) for more information.

I tried downgrading the mocha to 3.x in above given repository and it's working fine.

**Comment by ert78gb** [comment] 2019-06-20 13:06
I will create a test matrix on the weekend that uses the latest version of 3 and 4 of the datastore

Last time when I tried on my Mac pro the 3.x exited correctly

**Comment by ert78gb** [comment] 2019-06-23 17:43
In the [logs](https://travis-ci.org/ert78gb/google-datastore-emulator/builds/549417787), you can see v3 works fine v4 hanging

**Comment by laljikanjareeya** [comment] 2019-07-02 14:56
@ert78gb try using `--exit` flag while executing tests via `mocha`.

**Comment by ert78gb** [comment] 2019-07-02 17:08
Never, it is hide the resource management problems. It was the reason why changed the default behavior of mocha and I agree with it

**Comment by stephenplusplus** [comment] 2019-08-22 20:48
@ert78gb I appreciate the reproduction case, but is it possible to narrow it down to the smallest possible scenario? This makes the debugging process a lot more straightforward, since in this case I would be able to bypass the custom classes and Docker integration.

**Comment by ert78gb** [comment] 2019-08-23 16:39
I will create a very simple example tomorrow.
The script will
- connect to the bucket
- and add a document

The script will not exist.
I am experiencing the same problem with the latest pupsub lib. I think one of the common components causes the problem. 
My guess is there is a timer to keep alive the connection or renew a token periodically.

**Comment by stephenplusplus** [comment] 2019-08-23 16:45
Thank you very much for your help!

**Comment by ert78gb** [comment] 2019-08-23 16:46
sure. I also would like to know what is the root cause :)

**Comment by ert78gb** [comment] 2019-08-25 13:41
@stephenplusplus Sorry for the late answer. But was very hard to reproduce the problem.

When I created the sample repo I can not reproduce the bug with the v4 of Datastore, so I tried to investigate what is the problem.

What happens in the datastore-emulator tests:
1) Start the Google Datastore emulator - my tool
2) Read/Write operation - Datastore client
3) Stop the Google Datastore emulator - my tool
4) mocha does not exist.

Mocha exists only when no pending event in the event loop.
Let's see a little bit deeper the process

1) Start the Google Datastore emulator - my tool
2) Read/Write operation - Datastore client
3) Stop the Google Datastore emulator - my tool
  3.1) Google Datastore emulator terminating
  3.2) Http2Channel of the grcp-js detects the connection breakings and [starts a timer](https://github.com/grpc/grpc-node/blob/ea2fd4b45c04f91468f077264d3802749ffcabf5/packages/grpc-js/src/channel.ts#L181) for the auto reconnection. It will an infinity
4) mocha does not exist.

The Http2Channel of the grcp-js has a close method. If I see well it stops the timer that blocks the exits of the event loop.

It is possible to add a close() method to the Datastore client that call Http2Channel.close()?
Or maybe add an auto-reconnect property to the Http2Channel. If the property true then the auto-reconnect supported if false then not.
Or ...
I don't know which solution is match better to Google coding style.

**Comment by ert78gb** [comment] 2019-09-02 18:31
@stephenplusplus What do you think about my prev comment?

**Comment by stephenplusplus** [comment] 2019-09-11 20:57
@ert78gb sorry for the delay. I have been working on this, but I'm still hoping you could present the issue in a way that's detached from the wrapper you've written. I've spent a lot of time trying to work within it and make sure any holes that might exist are plugged, but there are too many variables to be able to track it down with confidence. As a start, maybe you could assume a Docker instance is already running and remove the standing up and tearing down logic? Ideally, something so small and using only our library that it leaves only us to blame 😆

**Comment by ert78gb** [comment] 2019-09-12 06:31
The small repo that contains only the datastore emulator code
https://github.com/ert78gb/google-datastore-client-not-exits

**Comment by stephenplusplus** [comment] 2019-09-17 16:39
I believe I have found a solution to expose the channel's close method. PR coming shortly!

**Comment by ert78gb** [comment] 2019-09-22 18:42
thx. I am waiting.

**Comment by stephenplusplus** [comment] 2019-09-22 22:09
Sorry for the lack of an update. Turns out there’s a bug with grpc that has an open PR for a fix: https://github.com/grpc/grpc-node/pull/1015. When that goes, the original behavior will be restored, and the script should exit as expected.

**Comment by bcoe** [comment] 2019-09-27 04:08
@stephenplusplus it looks like the upstream work for `grpc` is merged, and a new library version was recently published.

@ert78gb can you confirm that things are working?

**Comment by ert78gb** [comment] 2019-09-28 08:06
With the `@grpc/grpc-js@0.6.2` works perfectly.
Can you upgrade the dependency and release a new version?
By default, the `npm i` does not install the latest version of it.

**Comment by bcoe** [comment] 2019-09-30 16:21
@ert78gb :+1: awesome, I'm glad this has addressed your issue. We will work on explicitly updating the version # of grpc this week. In the mean time, I think you should get the desired effect by `rm -rf package-lock.json; rm -rf node_modules`, in a project.

I'm going to go ahead and close this issue since the underlying issue is addressed. Let me know if you bump into any more issues.

**Closed by bcoe** 2019-09-30 16:21 UTC
Labels: priority: p2, status: blocked, type: bug
