### ISSUE TITLE
Error: 13 INTERNAL: Failed to start HTTP/2 stream

### ISSUE THREAD

**Issue by ShwetaGhenand** [googleapis/nodejs-datastore#723] opened 2020-08-27 12:36 UTC
Hi,

This error seems to happen intermittently. 

```
Error: 13 INTERNAL: Failed to start HTTP/2 stream
    at Object.callErrorFromStatus (/src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.cancelWithStatus (/src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:457:14)
    at /src/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:209:48
    at runMicrotasks (<anonymous>)
```

#### Environment details

  - OS: Cloud Run
  - Node.js version: v14.8.0
  - npm version: 6.14.7
  - `@google-cloud/datastore` version: 4.5.2

Thanks!

**Comment by stephenplusplus** [comment] 2020-08-31 15:02
Thanks for opening. Node v14 isn't actually supported (https://github.com/googleapis/nodejs-datastore#supported-nodejs-versions), as it won't be "Active" until late October. If you downgrade to v12, do you still have the issues?

Also, additional information about how we can reproduce would be very helpful. Is it any API call you make through this library, or one? Can you reproduce it reliably under a certain amount of stress? Anything else that would help us dig in is great.

**Comment by ShwetaGhenand** [comment] 2020-09-02 12:06
> Thanks for opening. Node v14 isn't actually supported (https://github.com/googleapis/nodejs-datastore#supported-nodejs-versions), as it won't be "Active" until late October. If you downgrade to v12, do you still have the issues?
> 
> Also, additional information about how we can reproduce would be very helpful. Is it any API call you make through this library, or one? Can you reproduce it reliably under a certain amount of stress? Anything else that would help us dig in is great.


Thanks for the response. This error occurs randomly, so difficult to reproduce it. There is no steps or information to reproduce it but it seems like, it occurred when there is a many concurrent requests issued.

**Comment by stx** [comment] 2020-10-01 19:57
Also just had this problem on Cloud Run. Started randomly. It wouldn't go away until a rebuild. Worked fine for weeks with no issues. Was on 14.2, downgraded to 12 in the meantime. Google APIs not used.

**Comment by stx** [comment] 2020-12-10 21:02
@stephenplusplus 

This also happens on Node 12 using the node:12-slim image and connecting to Firestore. Isn't incurred by load, inactivity or volume. This is an extraordinarily severe issue to be happening randomly on stable production environments. I guarantee there are a number of customers experiencing this because we're not doing anything remotely special and 100% of requests fail.

**Comment by jaygrestoplus** [comment] 2020-12-11 00:37
Hi there, we've encountered this one too just today. We're also using `node:12-slim` as our image.

**Comment by stx** [comment] 2020-12-11 00:38
@jaygrestoplus Do you have timestamps for that? I'm wondering if this is a GCP infrastructure issue.

**Comment by maxwell-oroark** [comment] 2021-02-12 18:11
> @stephenplusplus
> 
> This also happens on Node 12 using the node:12-slim image and connecting to Firestore. Isn't incurred by load, inactivity or volume. This is an extraordinarily severe issue to be happening randomly on stable production environments.
> 
> I guarantee there are a number of customers experiencing this because we're not doing anything remotely special and 100% of requests fail until the instances are replaced. Our code is literally just an Admin SDK call through an Express route on a vanilla Docker image. Routes without Admin SDK calls perform correctly.

Adding that this also happened to our production environment app-engine app node12 API connecting to firebase admin SDK

**Comment by crwilcox** [comment] 2021-02-12 23:31
https://www.npmjs.com/package/@grpc/grpc-js just released an update that adds additional information to these errors. If you update dependencies (this is used by google-gax which is used by this library) and can share additional error information it may help us get to the root cause.

**Comment by stx** [comment] 2021-02-12 23:36
@crwilcox What's the best practice to do this, given that most of us aren't using this package directly, and are using things like "firebase-admin" and "googleapis"? If we explicitly include grpc-js, will that update what firebase-admin and googleapis use, and is that safe to do?

**Comment by murgatroid99** [comment] 2021-02-12 23:40
The new grpc-js release is a patch release that should still match the version range google-gax uses, so whatever you normally do to update dependencies should pick it up.

**Comment by crwilcox** [comment] 2021-02-12 23:41
The version range should still match and the dependency should update. `npm --depth 9999 update`

**Comment by crwilcox** [comment] 2021-02-23 23:57
@stx I just re-read the thread top to bottom and noticed "Google APIs not used."

To confirm, you experienced this same error, using gRPC, but not this particular library? I am wondering if we shouldn't move this to a gRPC lib to broaden discussion.

**Comment by stx** [comment] 2021-02-24 00:28
Yes, it also happens with firebase-admin because it uses gRPC upstream. Probably happens with other libraries too.

Would be nice to find someone that takes responsibility to fix it so the tech infra works properly in a basic scenario...

**Comment by crwilcox** [comment] 2021-02-24 00:39
The underlying code for firebase-admin (google-cloud/firestore) and datastore aren't all that different. Have you seen this in a non google grpc library?

**Comment by stx** [comment] 2021-02-24 01:20
No, haven't tried.

**Comment by stx** [comment] 2021-03-04 18:38
Just happened yet again on production with grpc 1.2.7.  No additional info logged so not sure what that's about.

{
  "error": "13 INTERNAL: Failed to start HTTP/2 stream"
}

**Comment by Joshandrews43** [comment] 2021-03-05 16:01
`firebase-admin@8.4.0` just had this happen to me in production for over 200 requests before I restarted my server and everything worked fine. Any solutions?

**Comment by stx** [comment] 2021-03-05 17:07
@Joshandrews43 What infrastructure is it running on? Cloud Run or something else?

**Comment by Joshandrews43** [comment] 2021-03-05 18:00
@stx Heroku web server running node 14.0.0. Any ideas?

**Comment by stx** [comment] 2021-03-05 18:01
@Joshandrews43 nodejs-datastore/firebase-admin or an upstream Google dependency is pretty clearly broken. There is no fix other than restarting it. Google Support says this has been a known issue for years. I have no idea how to get it taken care of.

**Comment by Joshandrews43** [comment] 2021-03-05 18:16
@stx a shame that one of the largest cloud providers in the world has a critical bug that effectively takes down your server and doesn't prioritize it...

**Comment by murgatroid99** [comment] 2021-03-05 19:25
@stx That exact error string no longer exists in `@grpc/grpc-js` >=1.2.7, so I think whichever dependency is triggering that error is still using an older version. Newer versions of the grpc-js library have more details in that error string so that when people report it we can use that information to figure this bug out.

**Comment by stx** [comment] 2021-03-05 19:30
@murgatroid99 Our package-lock.json lists `"@grpc/grpc-js": { "version": "1.2.7" }` but I can see that many Google packages are using less than that. I thought this would make it use 1.2.7?

**Comment by stx** [comment] 2021-03-05 19:35
I see that `@google-cloud/firestore` locked grpc to `"version": "1.0.5"` so I'm guessing that was the issue.

**Comment by murgatroid99** [comment] 2021-03-08 20:50
@stx Have you tried removing the `package-lock.json` file so that `npm install` picks up the new version of the dependency?

**Comment by stx** [comment] 2021-03-08 21:08
@murgatroid99 Yep, did that to begin with but packages still listed hardcoded old grpc versions that it appears were being used instead. Did another round of updating all of our Google package dependencies so I think grpc 1.2.7+ will be used now and we'll see what info it provides the next go around.

**Comment by crwilcox** [comment] 2021-03-11 18:52
We are looking into this, but the nature of this particular issue is rather hard to pin down. Also, from our investigations, it is likely that this is in fact smaller issues surfacing under a common symptom. The error that is being surfaced is an HTTP/2 error. RST_STREAM has many sub codes, though INTERNAL generally means either 'we don't know what went wrong' or 'something went wrong on the backend of things'. 

We have addressed some issues already, though I think there are some left for sure.

What would be helpful is to understand what call you are making when that error occurs. This issue isn't widespread and seems to exist in certain corners. Any information you can provide will help us further reduce these irritating messages.

I can say *generally* if it happens on a read-only operation, you could retry. If you are in a write operation, I can't be certain that there was no backend change on the error. It is however unlikely.

@stx thanks for adding that. We did make changes that should increase the amount of information provided.

**Comment by stx** [comment] 2021-03-11 19:17
@crwilcox Retries absolutely do not fix it (and really, have nothing to do with it.) The requests perpetually timeout forever until instances are restarted. I'm sure there are multiple causes of this, but the issue @Joshandrews43 and I are describing isn't a random irritating message, it's an outage. So we might not be talking about the same issue here. 

Here's a complete reproduction:

```
const express = require('express');
const admin = require('firebase-admin');
var app = module.exports = express();

app.get('/test', async (_, res) => {
  await admin.firestore().collection('users').where('thing', '==', 'true').get();
  res.send("Success");
});

app.get('/works', async (_, res) => {
  res.send("Success");
});
```

`/test` will start to randomly fail forever with the message outlined in this issue.
`/works` will work forever.

Replace Firestore with Datastore (and firestore-admin with nodejs-datastore) and the problem remains.

**Comment by murgatroid99** [comment] 2021-03-11 19:30
@stx The issue with this error causing subsequent requests to fail looks like a bug that was fixed in `@grpc/grpc-js` version 1.1.2.

**Comment by stx** [comment] 2021-03-11 19:31
@murgatroid99 Awesome! Fingers crossed.

**Comment by crwilcox** [comment] 2021-03-11 19:36
Thanks @murgatroid99! And thanks @stx. I crossed streams of two issues in my head. Sorry for the confusion :)

**Comment by crwilcox** [comment] 2021-07-22 21:33
In order for us to gather feedback better, please add any further details to the Firestore issue at https://github.com/googleapis/nodejs-firestore/issues/1023. The root cause is likely the same and it seems better to gather feedback in a single place. Feel free to add there if you see an issue.

**Closed** 2022-05-10 18:48 UTC
Labels: priority: p2, type: bug, external, api: datastore
