### ISSUE TITLE
Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)

### ISSUE THREAD

**Issue by penguinsource** [googleapis/nodejs-datastore#813] opened 2021-04-09 19:38 UTC
1) Is this a client library issue or a product issue?
This is a client library issue.

2) Did someone already solve this?
I have seen several posts about it but no solution so far. I am looking to understand the root cause so I know how to avoid it best.

3) Do you have a support contract?
No

The error is as follows and it comes up frequently and it's a big problem!

```
Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at process.nextTick (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 13,
  details: 'Received RST_STREAM with code 2 (Internal server error)',
  metadata: Metadata { internalRepr: Map {}, options: {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }"
```

- It occurs mostly on GET calls but I don't see many other patterns emerging otherwise. It happens way too often for a database library to be considered stable, unfortunately. Is there any solution or any workaround?

#### Environment details

  - OS: App Engine servers
  - Node.js version: 12.13.0
  - npm version: 6.12.0
  - `@google-cloud/datastore` version: 6.3.1

**Comment by crwilcox** [comment] 2021-04-19 16:02
I am marking this as a duplicate of https://github.com/googleapis/nodejs-datastore/issues/679. Please add any context there if you believe what you have experienced isn't captured.

**Closed by crwilcox** 2021-04-19 16:02 UTC
Labels: :rotating_light:, api: datastore, priority: p2, triage me, type: bug
